language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: Pw6zaXj6Rhylyw9yP34pLCaPOkSc2KP6eOGN9nD1+cu990wwdj6PiDGUqqb0UPcjlnbFDx6u71mH1ySEBhkNKs9SfO+GKeabHBuTzJ1fWSiMGd0Y1BAo0bqFO8l1DdAiDVsRp1+WL7Jn5XXEaVn4Y0lK756jHvTJHhF1DA+a3sk=
  app: kikansys
  on:
    repo: NoguHiro/kikan_system_01
